backend:
  name: github
  repo: FranGoofy/tamasora
  branch: main
  base_url: https://sveltia-cms-auth.franbookmmo.workers.dev

media_folder: z_Images/uploads
public_folder: /z_Images/uploads

collections:
  - name: sxs_characters
    label: "SxS Player Characters"
    folder: "Characters/SxS PCs"
    create: true
    extension: md
    fields:
      - { label: "Publish to Wiki", name: "publish", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: scribes_characters
    label: "Scribes Player Characters"
    folder: "Characters/Scribes PCs"
    create: true
    extension: md
    fields:
      - { label: "Publish to Wiki", name: "publish", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: recaps
    label: "Recaps"
    folder: "a_Recaps"
    create: true
    extension: md
    nested:
      depth: 100
    fields:
      - { label: "Publish to Wiki", name: "publish", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
